# ===== Thông tin cơ bản của ứng dụng =====
name: namer_app                         # Tên của ứng dụng Flutter
description: "A new Flutter project."  # Mô tả ngắn về ứng dụng
publish_to: 'none'                     # Không publish lên pub.dev (dự án dùng nội bộ)
version: 0.1.0                         # Phiên bản của ứng dụng: major.minor.patch+build

# ===== Thiết lập môi trường SDK Dart =====
environment:
  sdk: ^3.8.0                          # Yêu cầu SDK Dart từ phiên bản 3.8.0 trở lên

# ===== Các gói thư viện cần thiết khi chạy app =====
dependencies:
  flutter:
    sdk: flutter                      # Gói Flutter chính, cần thiết để build ứng dụng
  english_words: ^4.0.0               # Gói sinh từ tiếng Anh ngẫu nhiên (dùng trong demo)
  provider: ^6.1.5                    # Gói quản lý trạng thái (state management) phổ biến

# ===== Các gói chỉ dùng trong quá trình phát triển / kiểm thử =====
dev_dependencies:
  flutter_test:
    sdk: flutter                      # Gói hỗ trợ test widget Flutter
  flutter_lints: ^5.0.0               # Gói quy tắc lint để kiểm tra chất lượng code

# ===== Cấu hình thêm cho Flutter =====
flutter:
  uses-material-design: true          # Cho phép dùng các widget Material Design
